name: Conditional Workflow

on:
  push:
    branches:
      - main
  issues:
    types: [opened, edited, milestoned, closed]
  pull_request:
    branches:
      - main
#   release:
#     types: [published]

jobs:
  conditional-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to run on push event
      - name: Run on push
        if: github.event_name == 'push'
        run: echo "push event made by $GITHUB_ACTOR at $(date)"

      # Step to run on issues event (opened, edited, milestoned)
      - name: Run on issues
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'milestoned' || github.event.action == 'closed')
        run: echo "a issue been ${{github.event.action}}"

      # Step to run on pull_request event
      - name: Run on pull_request
        if: github.event_name == 'pull_request'
        run: echo "a pull request been made by $GITHUB_ACTOR at $(date)"

      # Step to run on release event
    #   - name: Run on release
    #     if: github.event_name == 'release' && github.event.action == 'published'
    #     run: echo "This step runs on release event (published)"